#!/bin/bash

if [ $# -ne 1 ]
then
    echo "1: Intro"
    echo "2: Diving into JS"
    echo "3: Advanced JS"
    echo "4: Git"
    exit 1
fi

function openApp {
    /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --app=$1
}

if [ "$1" == "1" ]
then
    openApp https://docs.google.com/presentation/d/1Sr8eMloaW3LSC8OGNbcwvkqQxNaJlfjGihZ76jLpw0w/pub
    exit 0
elif [ "$1" == "2" ]
then
    openApp https://docs.google.com/presentation/d/1uJUgAPVALNxlrAzpqN9ilFQrmC7OMXl9AWh9cvzYBoM/pub
    exit 0
elif [ "$1" == "3" ]
then
    openApp https://docs.google.com/presentation/d/1PONBRlUctkFcyCLuiA4RBWVjK2hKyTpV9UR1D_bMYYQ/pub
    exit 0
elif [ "$1" == "4" ]
then
    openApp https://docs.google.com/presentation/d/1p7_Xmbx9XhEGVScd1Qh2-9GGEvjuo0jVQ6Ptz6A3a9Y/pub
    exit 0
fi
